// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type Kubernetes struct {
	Kubeconfig string `mapstructure:"kubeconfig"`
	CacheDir string `mapstructure:"cache-dir"`
	ClientCertificate string `mapstructure:"client-certificate"`
	ClientKey string `mapstructure:"client-key"`
	Token string `mapstructure:"token"`
	As string `mapstructure:"as"`
	AsUid string `mapstructure:"as-uid"`
	AsGroup []string `mapstructure:"as-group"`
	Username string `mapstructure:"username"`
	Password string `mapstructure:"password"`
	Cluster string `mapstructure:"cluster"`
	User string `mapstructure:"user"`
	Namespace string `mapstructure:"namespace"`
	Context string `mapstructure:"context"`
	Server string `mapstructure:"server"`
	TlsServerName string `mapstructure:"tls-server-name"`
	InsecureSkipTlsVerify bool `mapstructure:"insecure-skip-tls-verify"`
	CertificateAuthority string `mapstructure:"certificate-authority"`
	RequestTimeout string `mapstructure:"request-timeout"`
	DisableCompression bool `mapstructure:"disable-compression"`
	SyncConfigMaps bool `mapstructure:"sync-config-maps"`
	SyncSecrets bool `mapstructure:"sync-secrets"`
	SyncPods bool `mapstructure:"sync-pods"`
	SyncNodes bool `mapstructure:"sync-nodes"`
	SyncDeployments bool `mapstructure:"sync-deployments"`
	SyncStatefulSets bool `mapstructure:"sync-stateful-sets"`
	SyncDaemonSets bool `mapstructure:"sync-daemon-sets"`
}

func (c *Kubernetes) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *Kubernetes) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Kubernetes) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	if t, ok := v.(string); ok {
		return t
	}
	if t, ok := v.([]byte); ok {
		return string(t)
	}
	panic("wrong type")
}

func (c *Kubernetes) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Kubernetes) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *Kubernetes) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
